<?php

/**
 * @file
 * Contains appointment.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function appointment_theme($existing, $type, $theme, $path): array
{
  return [
    'appointment_results' => [
      'variables' => [
        'items' => [],
      ],
      'template' => 'appointment-results',
    ],
    'appointment_customer_email' => [
      'template' => 'appointment-customer-email',
      'variables' => ['params' => []],
    ],
    'appointment_advisor_email' => [
      'template' => 'appointment-advisor-email',
      'variables' => ['params' => []],
    ],
    'agency_selection' => [
      'variables' => [
        'agencies' => [],
        'selected_agency' => '',
      ],
      'template' => 'agency-selection',
    ],
    'client_info_select' => [
      'variables' => [
        'start_time' => '',
        'end_time' => '',
        'date' => '',
      ],
      'template' => 'client-info-select',
    ],
    'appointment_type_selection' => [
      'variables' => [
        'types' => [],
        'selected_type' => '',
      ],
      'template' => 'appointment-type-selection',
    ],
    'advisor_selection' => [
      'variables' => [
        'advisors' => [],
        'selected_advisor' => '',
      ],
      'template' => 'advisor-selection',
    ],
    'rdv_details' => [
      'variables' => [
        'date' => '',
        'start_time' => '',
        'end_time' => '',
      ],
      'template' => 'rdv-details',
    ],
    'user_details' => [
      'variables' => [
        'rdv' => [],
      ],
      'template' => 'user-details',
    ],
    'success_appointment' => [
      'template' => 'success-appointment',
    ],
  ];
}

/**
 * Implements hook_help().
 */
function appointment_help($route_name, RouteMatchInterface $route_match)
{
  if ($route_name == 'help.page.appointment') {
    return '<p>' . t('This module provides a multi-step form for creating appointments.') . '</p>';
  }
}


/**
 * Implements hook_mail().
 */
function appointment_mail($key, &$message, $params)
{
  switch ($key) {
    case 'appointment_confirmation':
      $message['subject'] = $params['subject'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      $message['headers']['MIME-Version'] = '1.0';

      // Make sure the body is a string, not a render array
      if (is_array($params['body'])) {
        $renderer = \Drupal::service('renderer');
        $body_html = $renderer->renderRoot($params['body']);
        $message['body'][] = $body_html;
      } else {
        $message['body'][] = $params['body'];
      }
      break;
    case 'test':
      $message['subject'] = $params['subject'];
      $message['body'][] = is_array($params['body']) ?
        \Drupal::service('renderer')->renderPlain($params['body']) :
        $params['body'];
      break;
  }
}
